SUMMARY = "Small, dependency-free, fast Python package to infer binary file types checking the magic numbers signature"
HOMEPAGE = "https://github.com/h2non/filetype.py"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://LICENSE;md5=cc0e8af5f14a75ce53b7b9db0f4bd91e"

SRC_URI[md5sum] = "ab967600474756193788e979dbd209b3"
SRC_URI[sha256sum] = "17a3b885f19034da29640b083d767e0f13c2dcb5dcc267945c8b6e5a5a9013c7"

BBCLASSEXTEND = "native nativesdk"
