SUMMARY = "The new Python SDK for Sentry.io"
DESCRIPTION = "This is the next line of the Python SDK \
for Sentry, intended to replace the raven package on PyPI."
HOMEPAGE = "https://github.com/getsentry/sentry-python"
LICENSE = "BSD-2-Clause"
LIC_FILES_CHKSUM = "file://LICENSE;md5=0c79f8d3c91fc847350efd28bfe0a341"

SRC_URI[md5sum] = "f3a8a04f3e97607c9e588fcd42be4692"
SRC_URI[sha256sum] = "c5a41eba2d27416c81c901fe86de887e356aec4df7afd3327c324b2b3db7e934"

PYPI_PACKAGE = "sentry-sdk"
inherit pypi
